---
- name: Install Apache
  ansible.builtin.package:
    name: apache2
    state: present

- name: Install PHP
  ansible.builtin.package:
    name: php
    state: present

- name: Install php-mysql
  ansible.builtin.package:
    name: php-mysql
    state: present

- name: Enable and start Apache service
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes